import { Router } from "express";
import { businessManagerIntegrationAuth, requireBusinessManagerScope, requireExactBusinessManagerScope } from "../middlewares/bmIntegrationAuth.js";
import * as controller from "../controllers/bm.realEstate.controller.js";

const router = Router();
const readScope = requireBusinessManagerScope("bm:real-estate:read");
const bookingScope = requireBusinessManagerScope("bm:real-estate:booking:write");
const deliveryScope = requireBusinessManagerScope("bm:real-estate:delivery:write");
const privacyScope = requireExactBusinessManagerScope("bm:real-estate:privacy:write");
router.get("/bm/real-estate/connector-identity", businessManagerIntegrationAuth, readScope, controller.connectorIdentity);
router.get("/bm/real-estate/properties", businessManagerIntegrationAuth, readScope, controller.searchProperties);
router.get("/bm/real-estate/properties/:propertyId", businessManagerIntegrationAuth, readScope, controller.getProperty);
router.get("/bm/real-estate/properties/:propertyId/inspection-slots", businessManagerIntegrationAuth, readScope, controller.listInspectionSlots);
router.get("/bm/real-estate/properties/:propertyId/inspection-slots/:slotId", businessManagerIntegrationAuth, readScope, controller.getInspectionSlot);
router.post("/bm/real-estate/inspection-bookings", businessManagerIntegrationAuth, bookingScope, controller.createInspectionBooking);
router.get("/bm/real-estate/inspection-bookings/:bookingId/status", businessManagerIntegrationAuth, readScope, controller.getInspectionBookingStatus);
router.get("/bm/real-estate/inspection-booking-commands/:commandId/status", businessManagerIntegrationAuth, readScope, controller.reconcileInspectionBooking);
router.post("/bm/real-estate/inspection-bookings/:bookingId/email-confirmation", businessManagerIntegrationAuth, deliveryScope, controller.sendInspectionConfirmation);
router.get("/bm/real-estate/inspection-deliveries/:operationRef/status", businessManagerIntegrationAuth, readScope, controller.getInspectionDeliveryStatus);
router.get("/bm/real-estate/inspection-delivery-commands/:commandId/status", businessManagerIntegrationAuth, readScope, controller.reconcileInspectionDelivery);
router.get("/bm/real-estate/property-workflows/:workflowRef/status", businessManagerIntegrationAuth, readScope, controller.getPropertyWorkflowStatus);
router.get("/bm/real-estate/knowledge", businessManagerIntegrationAuth, readScope, controller.searchKnowledge);
router.post("/bm/real-estate/privacy/subject-data/access", businessManagerIntegrationAuth, privacyScope, controller.getInspectionPrivacyData);
router.post("/bm/real-estate/privacy/subject-data/redact", businessManagerIntegrationAuth, privacyScope, controller.redactInspectionPrivacyData);
export default router;
