export const PDF_ENGINE_VERSION = "TPR-PDFKIT-V3-2026-04-13.87";
export const PLANNING_SNAPSHOT_VERSION = "TPR-PLANNING-V2-2026-04-13.2";

const templateBase =
  String(process.env.TOWNPLANNER_REPORT_TEMPLATE_VERSION || "").trim() ||
  "TPR-PDFKIT-V3";

export const REPORT_TEMPLATE_VERSION = `${templateBase}::${PDF_ENGINE_VERSION}`;
export const PROPERTY_REPORT_VERSION =
  `${REPORT_TEMPLATE_VERSION}::${PLANNING_SNAPSHOT_VERSION}`;
