import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  SOPHIA_RUNTIME_CONTRACT_VERSION,
  SophiaRuntimeV2Schemas,
} from "../src/platform/contracts/v2/sophia-runtime-v2.contracts.js";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const runtimeRoot = resolve(scriptDirectory, "..");
const workspaceRoot = resolve(runtimeRoot, "../..");
const jsonOutput = resolve(runtimeRoot, "contracts/generated/sophia-runtime-v2.schema.json");
const backendTypeOutput = resolve(runtimeRoot, "contracts/generated/sophia-runtime-v2.contracts.ts");
const frontendTypeOutput = resolve(workspaceRoot, "frontend/src/app/sophia-runtime/contracts/generated/sophia-runtime-v2.contracts.ts");

const schemas = Object.fromEntries(
  Object.entries(SophiaRuntimeV2Schemas).map(([name, schema]) => [
    name,
    z.toJSONSchema(schema, { target: "draft-2020-12" }),
  ]),
);
const digestInput = stableStringify({
  contractVersion: SOPHIA_RUNTIME_CONTRACT_VERSION,
  schemas,
});
const schemaDigest = createHash("sha256").update(digestInput).digest("hex");
const jsonArtifact = `${JSON.stringify({
  contractVersion: SOPHIA_RUNTIME_CONTRACT_VERSION,
  schemaDigest,
  schemas,
}, null, 2)}\n`;
const typesArtifact = renderTypes(schemas, schemaDigest);

if (process.argv.includes("--check")) {
  await Promise.all([
    assertCurrent(jsonOutput, jsonArtifact),
    assertCurrent(backendTypeOutput, typesArtifact),
    assertCurrent(frontendTypeOutput, typesArtifact),
  ]);
} else {
  await Promise.all([
    mkdir(dirname(jsonOutput), { recursive: true }),
    mkdir(dirname(frontendTypeOutput), { recursive: true }),
  ]);
  await Promise.all([
    writeFile(jsonOutput, jsonArtifact),
    writeFile(backendTypeOutput, typesArtifact),
    writeFile(frontendTypeOutput, typesArtifact),
  ]);
}

async function assertCurrent(path: string, expected: string): Promise<void> {
  const actual = await readFile(path, "utf8").catch(() => "");
  if (actual !== expected) {
    throw new Error(`Generated contract artifact is stale: ${path}`);
  }
}

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right));
    return `{${entries.map(([key, entry]) => `${JSON.stringify(key)}:${stableStringify(entry)}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function renderTypes(schemaMap: Record<string, unknown>, digest: string): string {
  const declarations = Object.entries(schemaMap).map(([name, schema]) =>
    `export type ${name} = ${schemaToType(schema as JsonSchema, 0)};`,
  );
  return [
    "// Generated by backend/sophia-runtime/scripts/generate-v2-contracts.mts. Do not edit.",
    `export const SOPHIA_RUNTIME_CONTRACT_VERSION = ${JSON.stringify(SOPHIA_RUNTIME_CONTRACT_VERSION)} as const;`,
    `export const SOPHIA_RUNTIME_SCHEMA_DIGEST = ${JSON.stringify(digest)} as const;`,
    "",
    ...declarations.flatMap((declaration) => [declaration, ""]),
  ].join("\n");
}

type JsonSchema = {
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  additionalProperties?: boolean | JsonSchema;
};

function schemaToType(schema: JsonSchema, depth: number): string {
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  const union = schema.anyOf ?? schema.oneOf;
  if (union) return union.map((entry) => schemaToType(entry, depth)).join(" | ");
  if (Array.isArray(schema.type)) {
    return schema.type.map((type) => schemaToType({ ...schema, type }, depth)).join(" | ");
  }
  if (schema.type === "array") return `Array<${schemaToType(schema.items ?? {}, depth + 1)}>`;
  if (schema.type === "object" || schema.properties || schema.additionalProperties) {
    if (!schema.properties && schema.additionalProperties && typeof schema.additionalProperties === "object") {
      return `Record<string, ${schemaToType(schema.additionalProperties, depth + 1)}>`;
    }
    const required = new Set(schema.required ?? []);
    const indent = "  ".repeat(depth);
    const childIndent = "  ".repeat(depth + 1);
    const properties = Object.entries(schema.properties ?? {}).map(([name, property]) =>
      `${childIndent}${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${schemaToType(property, depth + 1)};`,
    );
    if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
      properties.push(`${childIndent}[key: string]: ${schemaToType(schema.additionalProperties, depth + 1)};`);
    }
    return `{\n${properties.join("\n")}\n${indent}}`;
  }
  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "null") return "null";
  return "unknown";
}
